font = "Misc Tamsyn"
font_size = 12.0

separator = "   "
[[modules]]
gravity = "left"
text = "browser"
#TODO background
left_click = "firefox"
[[modules]]
gravity = "left"
text = "terminal"
#TODO background
left_click = "alacritty"
[[modules]]
gravity = "left"
text = "poweroff"
left_click = "systemctl poweroff"
[[modules]]
gravity = "left"
text = "reboot"
left_click = "systemctl reboot"
[[modules]]
gravity = "left"
text = "suspend"
left_click = "systemctl suspend"
[[modules]]
gravity = "right"
exec = "date +%H:%M"
[[modules]]
gravity = "right"
exec = "./module-scripts/battery.sh"
[[modules]]
gravity = "right"
exec = "./module-scripts/volume.sh"
left_click = "pamixer --toggle-mute"
wheel_up = "pamixer --increase 1"
wheel_down = "pamixer --decrease 1"
[[modules]]
gravity = "right"
exec = "./module-scripts/brightness.sh"
wheel_up = "./module-scripts/brightness.sh up"
wheel_down = "./module-scripts/brightness.sh down"
[[modules]]
gravity = "right"
exec = "./module-scripts/network.sh"
