[[modules]]
text = "browser"
gravity = "left"
[[modules]]
text = "   "
gravity = "left"
[[modules]]
text = "terminal"
gravity = "left"
[[modules]]
text = "   "
gravity = "left"
[[modules]]
text = "shutdown"
gravity = "left"
[[modules]]
exec = "date +%H:%M"
gravity = "right"
[[modules]]
text = "   "
gravity = "right"
[[modules]]
exec = "./module-scripts/battery.sh"
gravity = "right"
[[modules]]
text = "   "
gravity = "right"
[[modules]]
exec = "./module-scripts/volume.sh"
gravity = "right"
[[modules]]
text = "   "
gravity = "right"
[[modules]]
exec = "./module-scripts/brightness.sh"
gravity = "right"
[[modules]]
text = "   "
gravity = "right"
[[modules]]
exec = "./module-scripts/network.sh"
gravity = "right"
